## Basics

In [2]:
import numpy as np

In [40]:
# np.array() initializes an array
# Below is a 1-dimensional array
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [41]:
# 2-dimensional array
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]]) # np.array([[row1 values], [row2values], etc.])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [42]:
# Get dimension of numpy array:
print(a.ndim) # ndim = number dimension
print(b.ndim)

1
2


In [43]:
# Get shape:
print(a.shape) # Prints number of elements since it's one-dimensional
print(b.shape) # Prints (# of rows, # of elements in each row)

(3,)
(2, 3)


In [62]:
# Get default data type:
print(a.dtype)
print(b.dtype)

int64
float64


In [63]:
# For small values like integers, you can specify smaller data types to be assigned to the array when initializing:
a = np.array([1, 2, 3], dtype='int16')
print(a.dtype)

int16


In [64]:
# Get the size of each element in the array (the number of bytes each one consists of):
a.itemsize

2

In [65]:
a = np.array([1, 2, 3], dtype='int64')
a.itemsize

8

In [79]:
# Get total number of elements in the array:
print(a.size)

# To find the total number of bytes your array consists of, do this:
print(a.size * a.itemsize)

# Or just do .nbytes (same thing):
print(a.nbytes)

3
24
24


## Accessing/Changing Specific Elements, Rows, Columns, etc.

In [85]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)
print(a.shape) # 2 by 7 array

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
(2, 7)


In [89]:
# Getting a specific element using a [row, column] index:
print(a[1, 5])
print(a[1, -2]) # Negative indexing is also possible with numpy

13
13


In [90]:
# Getting a specific row:
print(a[0, :]) # : Just returns all all columns/elements

[1 2 3 4 5 6 7]


In [93]:
# Getting a specific column:
print(a[:, 2]) 

[ 3 10]


In [103]:
# Getting more complex. To return multiple elements from a particular row, while also skipping every other element in the range:
# [row, start_index:end_index:step_size]
print(a[0, 1:6:2])
print(a[0, 1:-1:2]) # Same thing

[2 4 6]
[2 4 6]


In [110]:
# Replacing a certain element:
a[1, 5] = 20 
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [124]:
# Replacing elements in a certain column -- in this example, in the third column (column with index 2):
a[:, 2] = 5 # Sets ALL elements in this column to 5
print(a)

print()

a[:, 2] = [1, 2] # To give each element in the column new specific values
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


### 3D Example:

In [129]:
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [133]:
# Get specific element (work outside in) -- To get element that is "4":
print(b[0, 1, 1]) # array[layer_index, row_index, element_index/"column"_index]

4


In [138]:
# You can also do stuff like this:
print(b[:, 1, :])

[[3 4]
 [7 8]]


In [142]:
# In cases like these, it helps to lower the dimension by each index. 
# This way, you can think of the index below like this:
# 1. Find the first layer (imagine multiple flat, 2D layers of paper to make a 3D object)
# 2. Now take that layer and think of it as a 2D array. Now you can think of the ":" as finding all the rows in the 2D array
# 3. Lastly, think of how a 2D array has columns. Now you can interpret the "1" as the second column of this 2D array
print(b[0, :, 1])

[2 4]


In [145]:
# You can also use this more complex indexing to replace multiple values:
b[:, 1, :] = [[9, 9], [8, 8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


## Initializing Different Types of Arrays

In [166]:
# Initialize an all-zeros matrix with np.zeros():
print(np.zeros([2, 3])) # 2D all-zeros matrix
print('-------------')
print(np.zeros([2, 3, 3])) # 3D all-zeros matrix
print('-------------')
print(np.zeros([2, 2, 3, 2])) # Even a 4D matrix

[[0. 0. 0.]
 [0. 0. 0.]]
-------------
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
-------------
[[[[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]]]


In [177]:
# You can also make an all-ones matrix with np.ones():
print(np.ones([4, 2, 2], dtype='int64')) 

[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]


In [180]:
# Use np.full([dimensions], number) to create a matrix of any number:
print(np.full([2, 2], 50))

[[50 50]
 [50 50]]


In [190]:
# Use np.full_like(array/matrix to model, number you want to fill) to create a matrix that has the shape of a previously initialized array or matrix
# For instance: creating a matrix modeled off of array a from earlier in this notebook:
print(a)
print()
print(np.full_like(a, 4))

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]

[[4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4]]


In [204]:
# Use np.random.rand(dimensions) to create a matrix of random numbers between 0 and 1
print(np.random.rand(4, 2, 3))

[[[0.0657812  0.37948211 0.9156551 ]
  [0.13990853 0.10125867 0.96132518]]

 [[0.25472244 0.14949959 0.50204802]
  [0.50616325 0.96260265 0.80718601]]

 [[0.54066282 0.59497579 0.17379696]
  [0.74313032 0.76042296 0.32075159]]

 [[0.84991578 0.14346426 0.94291657]
  [0.0208821  0.7520723  0.89286714]]]


In [230]:
# To create a matrix of these random numbers AND assume the shape of a preexisting array:
print(np.random.random_sample(a.shape))

[[0.52893364 0.56021304 0.8323118  0.69615017 0.29180819 0.04224451
  0.91983993]
 [0.25822733 0.73444107 0.76595182 0.64339486 0.12810513 0.13536952
  0.28421853]]


In [240]:
# To fill with random integer values:
print(np.random.randint(-10, 8, size=[3, 3])) # np.random.randint(lowest int, int limit (exclusive), shape/size of array)

[[  7   0  -4]
 [ -5  -3  -8]
 [  1   0 -10]]


In [246]:
# To create an identity matrix (2D by default, so you only need to specify number of rows):
print(np.identity(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [261]:
# To repeat each value in an array:
arr = np.array([1, 2, 3])
repeat_arr = np.repeat(arr, 3) # np.repeat(arr whose values will be repeated, # of repeats)
print(repeat_arr)
print()

# To repeat these SETS of values, not just each individual value:
arr = np.array([[1, 2, 3]]) # Make the array 2D by adding an extra square brackets. 
repeat_arr = np.repeat(arr, 3, axis=0) 
# The axis=0 will then search for the horizontal axis of the 2D array (which is the [1, 2, 3]), and take that whole thing to repeat 3 times:
print(repeat_arr)
print()

# Similarly, if you do axis=1, that repeats each column in the 2D array, which is just each individual number like in the first example:
repeat_arr = np.repeat(arr, 3, axis=1)
print(repeat_arr)

[1 1 1 2 2 2 3 3 3]

[[1 2 3]
 [1 2 3]
 [1 2 3]]

[[1 1 1 2 2 2 3 3 3]]


### Challenge: Make a 5x5 array with all 1s in the outer ring, all 0s in the middle ring, and a 9 in the center of the array.

In [288]:
arr = np.ones([5, 5], dtype='int64')
arr[1:4, 1:4] = 0
arr[2, 2] = 9
print(arr)
print()

# Alternative method:
arr = np.ones([5, 5], dtype='int64')
inner = np.zeros([3, 3], dtype='int64')
inner[1, 1] = 9
arr[1:4, 1:4] = inner
print(arr)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### Be careful when copying arrays!

In [296]:
a = np.array([1, 2, 3])
b = a # When trying to copy one array to another like this, any changes you make to EITHER will change BOTH.
b[0] = 100
print(a) # a got the 100 as well even though it was supposed to be assigned only for b 
print()

# To fix this, use .copy():
a = np.array([1, 2, 3])
b = a.copy()
b[0] = 100
print(a) # a maintains its values

[100   2   3]

[1 2 3]


## NumPy Mathematics

In [320]:
a = np.array([1, 2, 3, 4])
print(a)

# Performs element-wise arithmetic:
print(a + 2)
print(a - 2)
print(a * 2)
print(a / 2)

[1 2 3 4]
[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]


In [322]:
# Update array variable to store the result of these element-wise calculations:
a += 2
print(a)

[1 2 3 4]


In [324]:
# You can also do element-wise calculations across two different arrays:
a = np.array([1, 2, 3, 4])
b = np.array([1, 0, 1, 0])
a += b
print(a)

[2 2 4 4]


In [326]:
# You can also do other stuff like find sine and cosine of each value:
print(np.sin(a))
print(np.cos(a))

[ 0.90929743  0.90929743 -0.7568025  -0.7568025 ]
[-0.41614684 -0.41614684 -0.65364362 -0.65364362]


### Linear Algebra

In [345]:
a = np.ones([2, 3], dtype='int64')
b = np.full([3, 2], 2)
print(a)
print(b)
print()

# To do matrix multiplication, the # of columns of the first matrix must be the same as the # of rows in the second.
# To perform matrix multiplication:
print(np.matmul(a, b))

[[1 1 1]
 [1 1 1]]
[[2 2]
 [2 2]
 [2 2]]

[[6 6]
 [6 6]]


There are many more applications of linear algebra in NumPy.

### Statistics

In [380]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
print(stats)
print(np.min(stats))
print(np.max(stats))

[[1 2 3]
 [4 5 6]]
1
6


In [381]:
print(np.min(stats, axis=0)) # Returns the min value in each column
print(np.max(stats, axis=1)) # Returns the max value in each row

[1 2 3]
[3 6]


In [386]:
# To sum up all elements:
print(np.sum(stats))

# To sum up elements in each column:
print(np.sum(stats, axis=0))

# To sum up elements in each row:
print(np.sum(stats, axis=1))

21
[5 7 9]
[ 6 15]


## Reorganizing Arrays

In [396]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)
print('Current shape of before:', before.shape)

[[1 2 3 4]
 [5 6 7 8]]
Current shape of before: (2, 4)


In [401]:
# To change the shape of this array, use array.reshape()
# ANY of the following examples work (including the last 3D example) as long as the reshaped array has the same number of values.
after = before.reshape(1, 8)
print(after)

[[1 2 3 4 5 6 7 8]]


In [402]:
after = before.reshape(4, 2)
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [403]:
after = before.reshape(2, 2, 2)
print(after)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [410]:
# Therefore, this will throw an error:
after = before.reshape(2, 3)

ValueError: cannot reshape array of size 8 into shape (2,3)

In [421]:
# Vertically stacking matrices:
# The number of columns MUST be the same
m1 = np.array([1, 2, 3, 4])
m2 = np.array([5, 6, 7, 8])

# np.vstack([matrix_1, matrix_2, etc.]) means "vertical stack." It just stacks the matrices on top of each other to make one big array.
print(np.vstack([m1, m2]))

[[1 2 3 4]
 [5 6 7 8]]


In [413]:
# You can also stack the same matrices multiple times:
print(np.vstack([m1, m2, m1, m2]))

[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]


In [424]:
# Horizontal stacking works basically the same:
# # The number of rows MUST be the same
h1 = np.ones([2, 4])
print(h1)
h2 = np.zeros([2, 2])
print(h2)
print()

print(np.hstack([h1, h2]))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]

[[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]]


## Miscellaneous

In [473]:
# To load local datasets into a NumPy array, use np.genfromtxt(path, delimiter='')
file_data = np.genfromtxt('./other-datasets/data.txt', delimiter=',', dtype='float64')
print(file_data)

[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]


In [474]:
# You can also cast an array's data type with array.astype('dtype'):
file_data = file_data.astype('int64') # Casts all elements as floats
print(file_data)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


### Boolean Masking and Advanced indexing

In [475]:
# You can use conditions like this one to test each element on, and NumPy will return an array with booleans in place
file_data > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [476]:
# You can also do indexing like you would in Pandas:
# In this case, you index by returning only the values that meet the condition inside the brackets
print(file_data[file_data > 50])

[196  75 766  75  55 999  78  76  88]


In [477]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(a[[1, 2, 8]]) # You can also index multiple positions like so

[2 3 9]


In [479]:
print(file_data)
print()
print(np.any(file_data > 50, axis=0)) 
# np.any() Returns true for each column (due to axis=0) that has ANY values that meet the condition within the parentheses

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]

[False False False False  True  True False  True  True False False False
 False False False False  True  True]


In [481]:
print(np.all(file_data > 50, axis=0))
# np.all() Returns true for each column (due to axis=0) with values that ALL meet the condition within the parentheses

[False False False False  True False False False False False False False
 False False False False False False]


In [493]:
# You can also return a boolean version of the array from multiple conditions:
~(file_data > 50) & (file_data < 100)

array([[ True,  True,  True,  True, False, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

## Challenge

1. Create an array with 6 rows and 5 columns of 30 elements that increment by 1 from the top left to the bottom right, starting at 1.
2. Use indexing to return this part of the array:
   <code>
   [[11 12]
    [16 17]]
   </code>
4. Use indexing to return the 2, 8, 14, and 20 in the array.
5. Use indexing to return these separate parts of the array:
   <code>
   [[4 5]
   [24 25]
   [29 30]]
   </code>

In [568]:
# 1.
arr = np.zeros([6, 5], dtype='int64')

row1 = np.array([1, 2, 3, 4, 5])
for i in range(len(arr)):
    arr[i] += row1
    row1 += 5
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [569]:
# 2.
print(arr[2:4, 0:2])

[[11 12]
 [16 17]]


In [570]:
# 3.
print(arr[[0, 1, 2, 3], [1, 2, 3, 4]])

[ 2  8 14 20]


In [571]:
# 4.
print(arr[[0, -2, -1], 3:])

[[ 4  5]
 [24 25]
 [29 30]]
